-- Drop enum types if no tables are using them
DROP TYPE IF EXISTS PHONE_VERIFICATION_STATUS;
DROP TYPE IF EXISTS PAN_VERIFICATION_STATUS;
DROP TYPE IF EXISTS EXTRA_DETAILS_COLLECTION_STATUS;
DROP TYPE IF EXISTS CONSENT_STAGE_STATUS;
DROP TYPE IF EXISTS LIVENESS_CHECK_STATUS;
