-- Create enum types if they don't exist
CREATE TYPE PHONE_VERIFICATION_STATUS AS ENUM (
    'PHONE_NOT_INITIATED',
    'PHONE_VERIFIED',
    'PHONE_PENDING',
    'PHONE_DECLINED'
    );

CREATE TYPE AADHAR_VERIFICATION_STATUS AS ENUM (
    'AADHAR_NOT_INITIATED',
    'AADHAR_VERIFIED',
    'AADHAR_PENDING',
    'AADHAR_DATA_NOT_FOUND',
    'AADHAR_DECLINED'
    );

CREATE TYPE PAN_VERIFICATION_STATUS AS ENUM (
    'PAN_VERIFICATION_NOT_INITIATED',
    'PAN_VERIFICATION_INITIATED',
    'PAN_NOT_FOUND',
    'PAN_OTP_SENT',
    'PAN_VERIFIED'
    );

CREATE TYPE EMPLOYMENT_TYPE AS ENUM (
    'Full-Time Salaried',
    'Part-Time Salaried',
    'Contractor',
    'Consultant',
    'Internship',
    'Freelancer',
    'Farmer',
    'Housewife',
    'Business Owner'
    );

CREATE TYPE EMAIL_VERIFICATION_TYPE AS ENUM (
    'EMAIL_VERIFICATION_NOT_INITIATED',
    'EMAIL_VERIFICATION_STARTED',
    'EMAIL_VERIFICATION_COMPLETED'
    );

CREATE TYPE CONSENT_STAGE_STATUS AS ENUM (
    'CONSENT_NOT_INITIATED',
    'CONSENT_NOTIFICATION',
    'CONSENT_BIOMETRIC',
    'CONSENT_COMPLETED'
    );

CREATE TYPE LIVENESS_CHECK_STATUS AS ENUM (
    'LIVENESS_NOT_INITIATED',
    'LIVENESS_STARTED',
    'LIVENESS_COMPLETED'
    );