-- Drop ENUM types
DROP TYPE IF EXISTS LIVENESS_CHECK_STATUS;
DROP TYPE IF EXISTS CONSENT_STAGE_STATUS;
DROP TYPE IF EXISTS EMPLOYMENT_TYPE;
DROP TYPE IF EXISTS PAN_VERIFICATION_STATUS;
DROP TYPE IF EXISTS AADHAR_VERIFICATION_STATUS;
DROP TYPE IF EXISTS PHONE_VERIFICATION_STATUS;
DROP TYPE IF EXISTS EMAIL_VERIFICATION_TYPE;
