// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0
// source: protos-frontend/enums/permission_types.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// PermissionType enumeration
// Represents different types of permissions
type PermissionType int32

const (
	// *
	// Notifications permission type
	// This value represents permission for notifications
	PermissionType_NOTIFICATIONS PermissionType = 0
	// *
	// Location permission type
	// This value represents permission for location access
	PermissionType_LOCATION PermissionType = 1
	// *
	// Terms and conditions permission
	PermissionType_TERMS_AND_CONDITIONS PermissionType = 2
	// *
	// Data sharing permission
	PermissionType_DATA_SHARING PermissionType = 3
	// *
	// Other types of permissions
	PermissionType_OTHER_PERMISSIONS PermissionType = 4
)

// Enum value maps for PermissionType.
var (
	PermissionType_name = map[int32]string{
		0: "NOTIFICATIONS",
		1: "LOCATION",
		2: "TERMS_AND_CONDITIONS",
		3: "DATA_SHARING",
		4: "OTHER_PERMISSIONS",
	}
	PermissionType_value = map[string]int32{
		"NOTIFICATIONS":        0,
		"LOCATION":             1,
		"TERMS_AND_CONDITIONS": 2,
		"DATA_SHARING":         3,
		"OTHER_PERMISSIONS":    4,
	}
)

func (x PermissionType) Enum() *PermissionType {
	p := new(PermissionType)
	*p = x
	return p
}

func (x PermissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_frontend_enums_permission_types_proto_enumTypes[0].Descriptor()
}

func (PermissionType) Type() protoreflect.EnumType {
	return &file_protos_frontend_enums_permission_types_proto_enumTypes[0]
}

func (x PermissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionType.Descriptor instead.
func (PermissionType) EnumDescriptor() ([]byte, []int) {
	return file_protos_frontend_enums_permission_types_proto_rawDescGZIP(), []int{0}
}

var File_protos_frontend_enums_permission_types_proto protoreflect.FileDescriptor

var file_protos_frontend_enums_permission_types_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x64, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2a, 0x74, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x54, 0x49, 0x46,
	0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x4f,
	0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x54, 0x45, 0x52, 0x4d,
	0x53, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x53,
	0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x53, 0x48, 0x41, 0x52, 0x49,
	0x4e, 0x47, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x50, 0x45,
	0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x53, 0x10, 0x04, 0x42, 0x30, 0x5a, 0x2e, 0x52,
	0x69, 0x6e, 0x6e, 0x65, 0x67, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66,
	0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_frontend_enums_permission_types_proto_rawDescOnce sync.Once
	file_protos_frontend_enums_permission_types_proto_rawDescData = file_protos_frontend_enums_permission_types_proto_rawDesc
)

func file_protos_frontend_enums_permission_types_proto_rawDescGZIP() []byte {
	file_protos_frontend_enums_permission_types_proto_rawDescOnce.Do(func() {
		file_protos_frontend_enums_permission_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_frontend_enums_permission_types_proto_rawDescData)
	})
	return file_protos_frontend_enums_permission_types_proto_rawDescData
}

var file_protos_frontend_enums_permission_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_frontend_enums_permission_types_proto_goTypes = []interface{}{
	(PermissionType)(0), // 0: enums.PermissionType
}
var file_protos_frontend_enums_permission_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_frontend_enums_permission_types_proto_init() }
func file_protos_frontend_enums_permission_types_proto_init() {
	if File_protos_frontend_enums_permission_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_frontend_enums_permission_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_frontend_enums_permission_types_proto_goTypes,
		DependencyIndexes: file_protos_frontend_enums_permission_types_proto_depIdxs,
		EnumInfos:         file_protos_frontend_enums_permission_types_proto_enumTypes,
	}.Build()
	File_protos_frontend_enums_permission_types_proto = out.File
	file_protos_frontend_enums_permission_types_proto_rawDesc = nil
	file_protos_frontend_enums_permission_types_proto_goTypes = nil
	file_protos_frontend_enums_permission_types_proto_depIdxs = nil
}
