// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0
// source: protos-frontend/enums/response_types.proto

// Define the package name

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// enum that identifies the state for the phone number verification response type
type VerificationResponseType int32

const (
	VerificationResponseType_VERIFICATION_RESPONSE_UNIDENTIFIED       VerificationResponseType = 0
	VerificationResponseType_VERIFICATION_RESPONSE_OTP_SENT           VerificationResponseType = 1
	VerificationResponseType_VERIFICATION_RESPONSE_INVALID_PARAMETERS VerificationResponseType = 2
	VerificationResponseType_VERIFICATION_RESPONSE_SERVER_FAILURE     VerificationResponseType = 3
)

// Enum value maps for VerificationResponseType.
var (
	VerificationResponseType_name = map[int32]string{
		0: "VERIFICATION_RESPONSE_UNIDENTIFIED",
		1: "VERIFICATION_RESPONSE_OTP_SENT",
		2: "VERIFICATION_RESPONSE_INVALID_PARAMETERS",
		3: "VERIFICATION_RESPONSE_SERVER_FAILURE",
	}
	VerificationResponseType_value = map[string]int32{
		"VERIFICATION_RESPONSE_UNIDENTIFIED":       0,
		"VERIFICATION_RESPONSE_OTP_SENT":           1,
		"VERIFICATION_RESPONSE_INVALID_PARAMETERS": 2,
		"VERIFICATION_RESPONSE_SERVER_FAILURE":     3,
	}
)

func (x VerificationResponseType) Enum() *VerificationResponseType {
	p := new(VerificationResponseType)
	*p = x
	return p
}

func (x VerificationResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_frontend_enums_response_types_proto_enumTypes[0].Descriptor()
}

func (VerificationResponseType) Type() protoreflect.EnumType {
	return &file_protos_frontend_enums_response_types_proto_enumTypes[0]
}

func (x VerificationResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationResponseType.Descriptor instead.
func (VerificationResponseType) EnumDescriptor() ([]byte, []int) {
	return file_protos_frontend_enums_response_types_proto_rawDescGZIP(), []int{0}
}

type LivenessCheckStatus int32

const (
	LivenessCheckStatus_LIVENESS_CHECK_STATUS_UNIDENTIFIED   LivenessCheckStatus = 0
	LivenessCheckStatus_LIVENESS_CHECK_STATUS_OTP_MATCHED    LivenessCheckStatus = 1
	LivenessCheckStatus_LIVENESS_CHECK_STATUS_INVALID_OTP    LivenessCheckStatus = 2
	LivenessCheckStatus_LIVENESS_CHECK_STATUS_SERVER_FAILURE LivenessCheckStatus = 3
)

// Enum value maps for LivenessCheckStatus.
var (
	LivenessCheckStatus_name = map[int32]string{
		0: "LIVENESS_CHECK_STATUS_UNIDENTIFIED",
		1: "LIVENESS_CHECK_STATUS_OTP_MATCHED",
		2: "LIVENESS_CHECK_STATUS_INVALID_OTP",
		3: "LIVENESS_CHECK_STATUS_SERVER_FAILURE",
	}
	LivenessCheckStatus_value = map[string]int32{
		"LIVENESS_CHECK_STATUS_UNIDENTIFIED":   0,
		"LIVENESS_CHECK_STATUS_OTP_MATCHED":    1,
		"LIVENESS_CHECK_STATUS_INVALID_OTP":    2,
		"LIVENESS_CHECK_STATUS_SERVER_FAILURE": 3,
	}
)

func (x LivenessCheckStatus) Enum() *LivenessCheckStatus {
	p := new(LivenessCheckStatus)
	*p = x
	return p
}

func (x LivenessCheckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LivenessCheckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_frontend_enums_response_types_proto_enumTypes[1].Descriptor()
}

func (LivenessCheckStatus) Type() protoreflect.EnumType {
	return &file_protos_frontend_enums_response_types_proto_enumTypes[1]
}

func (x LivenessCheckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LivenessCheckStatus.Descriptor instead.
func (LivenessCheckStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_frontend_enums_response_types_proto_rawDescGZIP(), []int{1}
}

type ErrorType int32

const (
	// Default value indicating an unknown error.
	ErrorType_UNKNOWN_ERROR ErrorType = 0
	// Error code indicating that the request is invalid.
	ErrorType_INVALID_REQUEST ErrorType = 1
	// Error code indicating that permission is denied for the operation.
	ErrorType_PERMISSION_DENIED ErrorType = 2
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_REQUEST",
		2: "PERMISSION_DENIED",
	}
	ErrorType_value = map[string]int32{
		"UNKNOWN_ERROR":     0,
		"INVALID_REQUEST":   1,
		"PERMISSION_DENIED": 2,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_frontend_enums_response_types_proto_enumTypes[2].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_protos_frontend_enums_response_types_proto_enumTypes[2]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_protos_frontend_enums_response_types_proto_rawDescGZIP(), []int{2}
}

var File_protos_frontend_enums_response_types_proto protoreflect.FileDescriptor

var file_protos_frontend_enums_response_types_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x64, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65, 0x6e,
	0x75, 0x6d, 0x73, 0x2a, 0xbe, 0x01, 0x0a, 0x18, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x26, 0x0a, 0x22, 0x56, 0x45, 0x52, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x55, 0x4e, 0x49, 0x44, 0x45, 0x4e,
	0x54, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x22, 0x0a, 0x1e, 0x56, 0x45, 0x52, 0x49,
	0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53,
	0x45, 0x5f, 0x4f, 0x54, 0x50, 0x5f, 0x53, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x2c, 0x0a, 0x28,
	0x56, 0x45, 0x52, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x53,
	0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x50, 0x41,
	0x52, 0x41, 0x4d, 0x45, 0x54, 0x45, 0x52, 0x53, 0x10, 0x02, 0x12, 0x28, 0x0a, 0x24, 0x56, 0x45,
	0x52, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f,
	0x4e, 0x53, 0x45, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55,
	0x52, 0x45, 0x10, 0x03, 0x2a, 0xb5, 0x01, 0x0a, 0x13, 0x4c, 0x69, 0x76, 0x65, 0x6e, 0x65, 0x73,
	0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x22,
	0x4c, 0x49, 0x56, 0x45, 0x4e, 0x45, 0x53, 0x53, 0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x25, 0x0a, 0x21, 0x4c, 0x49, 0x56, 0x45, 0x4e, 0x45, 0x53, 0x53,
	0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x54,
	0x50, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x45, 0x44, 0x10, 0x01, 0x12, 0x25, 0x0a, 0x21, 0x4c,
	0x49, 0x56, 0x45, 0x4e, 0x45, 0x53, 0x53, 0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4f, 0x54, 0x50,
	0x10, 0x02, 0x12, 0x28, 0x0a, 0x24, 0x4c, 0x49, 0x56, 0x45, 0x4e, 0x45, 0x53, 0x53, 0x5f, 0x43,
	0x48, 0x45, 0x43, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x45, 0x52, 0x56,
	0x45, 0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x03, 0x2a, 0x4a, 0x0a, 0x09,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10,
	0x01, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f,
	0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x10, 0x02, 0x42, 0x30, 0x5a, 0x2e, 0x52, 0x69, 0x6e, 0x6e,
	0x65, 0x67, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x64, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_frontend_enums_response_types_proto_rawDescOnce sync.Once
	file_protos_frontend_enums_response_types_proto_rawDescData = file_protos_frontend_enums_response_types_proto_rawDesc
)

func file_protos_frontend_enums_response_types_proto_rawDescGZIP() []byte {
	file_protos_frontend_enums_response_types_proto_rawDescOnce.Do(func() {
		file_protos_frontend_enums_response_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_frontend_enums_response_types_proto_rawDescData)
	})
	return file_protos_frontend_enums_response_types_proto_rawDescData
}

var file_protos_frontend_enums_response_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protos_frontend_enums_response_types_proto_goTypes = []interface{}{
	(VerificationResponseType)(0), // 0: enums.VerificationResponseType
	(LivenessCheckStatus)(0),      // 1: enums.LivenessCheckStatus
	(ErrorType)(0),                // 2: enums.ErrorType
}
var file_protos_frontend_enums_response_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_frontend_enums_response_types_proto_init() }
func file_protos_frontend_enums_response_types_proto_init() {
	if File_protos_frontend_enums_response_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_frontend_enums_response_types_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_frontend_enums_response_types_proto_goTypes,
		DependencyIndexes: file_protos_frontend_enums_response_types_proto_depIdxs,
		EnumInfos:         file_protos_frontend_enums_response_types_proto_enumTypes,
	}.Build()
	File_protos_frontend_enums_response_types_proto = out.File
	file_protos_frontend_enums_response_types_proto_rawDesc = nil
	file_protos_frontend_enums_response_types_proto_goTypes = nil
	file_protos_frontend_enums_response_types_proto_depIdxs = nil
}
