// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: wealth/wealth_service.proto

package wealth

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

// WealthServiceClient is the client API for WealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define the service
type WealthServiceClient interface {
}

type wealthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWealthServiceClient(cc grpc.ClientConnInterface) WealthServiceClient {
	return &wealthServiceClient{cc}
}

// WealthServiceServer is the server API for WealthService service.
// All implementations must embed UnimplementedWealthServiceServer
// for forward compatibility
//
// Define the service
type WealthServiceServer interface {
	mustEmbedUnimplementedWealthServiceServer()
}

// UnimplementedWealthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWealthServiceServer struct {
}

func (UnimplementedWealthServiceServer) mustEmbedUnimplementedWealthServiceServer() {}

// UnsafeWealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WealthServiceServer will
// result in compilation errors.
type UnsafeWealthServiceServer interface {
	mustEmbedUnimplementedWealthServiceServer()
}

func RegisterWealthServiceServer(s grpc.ServiceRegistrar, srv WealthServiceServer) {
	s.RegisterService(&WealthService_ServiceDesc, srv)
}

// WealthService_ServiceDesc is the grpc.ServiceDesc for WealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wealth.WealthService",
	HandlerType: (*WealthServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "wealth/wealth_service.proto",
}
