// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0
// source: protos-frontend/deeplink/deeplink.proto

package deeplink

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Deeplink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Pod:
	//
	//	*Deeplink_OnboardingDeeplink
	//	*Deeplink_HomeDeeplink
	Pod isDeeplink_Pod `protobuf_oneof:"Pod"`
}

func (x *Deeplink) Reset() {
	*x = Deeplink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_frontend_deeplink_deeplink_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deeplink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deeplink) ProtoMessage() {}

func (x *Deeplink) ProtoReflect() protoreflect.Message {
	mi := &file_protos_frontend_deeplink_deeplink_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deeplink.ProtoReflect.Descriptor instead.
func (*Deeplink) Descriptor() ([]byte, []int) {
	return file_protos_frontend_deeplink_deeplink_proto_rawDescGZIP(), []int{0}
}

func (m *Deeplink) GetPod() isDeeplink_Pod {
	if m != nil {
		return m.Pod
	}
	return nil
}

func (x *Deeplink) GetOnboardingDeeplink() *OnboardingPodDeeplink {
	if x, ok := x.GetPod().(*Deeplink_OnboardingDeeplink); ok {
		return x.OnboardingDeeplink
	}
	return nil
}

func (x *Deeplink) GetHomeDeeplink() *HomePodDeeplink {
	if x, ok := x.GetPod().(*Deeplink_HomeDeeplink); ok {
		return x.HomeDeeplink
	}
	return nil
}

type isDeeplink_Pod interface {
	isDeeplink_Pod()
}

type Deeplink_OnboardingDeeplink struct {
	OnboardingDeeplink *OnboardingPodDeeplink `protobuf:"bytes,1,opt,name=onboarding_deeplink,json=onboardingDeeplink,proto3,oneof"`
}

type Deeplink_HomeDeeplink struct {
	HomeDeeplink *HomePodDeeplink `protobuf:"bytes,2,opt,name=home_deeplink,json=homeDeeplink,proto3,oneof"`
}

func (*Deeplink_OnboardingDeeplink) isDeeplink_Pod() {}

func (*Deeplink_HomeDeeplink) isDeeplink_Pod() {}

var File_protos_frontend_deeplink_deeplink_proto protoreflect.FileDescriptor

var file_protos_frontend_deeplink_deeplink_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x64, 0x2f, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x64, 0x65, 0x65, 0x70, 0x6c,
	0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x65, 0x65, 0x70, 0x6c,
	0x69, 0x6e, 0x6b, 0x1a, 0x33, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x64, 0x2f, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x6f, 0x6e,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x69, 0x6e,
	0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x69,
	0x6e, 0x6b, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x69, 0x6e, 0x6b,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x08, 0x44, 0x65, 0x65, 0x70,
	0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x52, 0x0a, 0x13, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69,
	0x6e, 0x67, 0x5f, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x4f, 0x6e, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x64, 0x44, 0x65, 0x65, 0x70, 0x6c, 0x69,
	0x6e, 0x6b, 0x48, 0x00, 0x52, 0x12, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x44, 0x65, 0x65, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x40, 0x0a, 0x0d, 0x68, 0x6f, 0x6d, 0x65,
	0x5f, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x50,
	0x6f, 0x64, 0x44, 0x65, 0x65, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x0c, 0x68, 0x6f,
	0x6d, 0x65, 0x44, 0x65, 0x65, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x42, 0x05, 0x0a, 0x03, 0x50, 0x6f,
	0x64, 0x42, 0x33, 0x5a, 0x31, 0x52, 0x69, 0x6e, 0x6e, 0x65, 0x67, 0x61, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x64, 0x65,
	0x65, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_frontend_deeplink_deeplink_proto_rawDescOnce sync.Once
	file_protos_frontend_deeplink_deeplink_proto_rawDescData = file_protos_frontend_deeplink_deeplink_proto_rawDesc
)

func file_protos_frontend_deeplink_deeplink_proto_rawDescGZIP() []byte {
	file_protos_frontend_deeplink_deeplink_proto_rawDescOnce.Do(func() {
		file_protos_frontend_deeplink_deeplink_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_frontend_deeplink_deeplink_proto_rawDescData)
	})
	return file_protos_frontend_deeplink_deeplink_proto_rawDescData
}

var file_protos_frontend_deeplink_deeplink_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_frontend_deeplink_deeplink_proto_goTypes = []interface{}{
	(*Deeplink)(nil),              // 0: deeplink.Deeplink
	(*OnboardingPodDeeplink)(nil), // 1: deeplink.OnboardingPodDeeplink
	(*HomePodDeeplink)(nil),       // 2: deeplink.HomePodDeeplink
}
var file_protos_frontend_deeplink_deeplink_proto_depIdxs = []int32{
	1, // 0: deeplink.Deeplink.onboarding_deeplink:type_name -> deeplink.OnboardingPodDeeplink
	2, // 1: deeplink.Deeplink.home_deeplink:type_name -> deeplink.HomePodDeeplink
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_frontend_deeplink_deeplink_proto_init() }
func file_protos_frontend_deeplink_deeplink_proto_init() {
	if File_protos_frontend_deeplink_deeplink_proto != nil {
		return
	}
	file_protos_frontend_deeplink_onboarding_deeplinks_proto_init()
	file_protos_frontend_deeplink_home_deeplinks_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_frontend_deeplink_deeplink_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deeplink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_frontend_deeplink_deeplink_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Deeplink_OnboardingDeeplink)(nil),
		(*Deeplink_HomeDeeplink)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_frontend_deeplink_deeplink_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_frontend_deeplink_deeplink_proto_goTypes,
		DependencyIndexes: file_protos_frontend_deeplink_deeplink_proto_depIdxs,
		MessageInfos:      file_protos_frontend_deeplink_deeplink_proto_msgTypes,
	}.Build()
	File_protos_frontend_deeplink_deeplink_proto = out.File
	file_protos_frontend_deeplink_deeplink_proto_rawDesc = nil
	file_protos_frontend_deeplink_deeplink_proto_goTypes = nil
	file_protos_frontend_deeplink_deeplink_proto_depIdxs = nil
}
