// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: protos-frontend/UI/Button.proto

// Define the package name

package UI

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// message to contain the information for a button component
type Button struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text         string        `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	BgColor      string        `protobuf:"bytes,2,opt,name=bg_color,json=bgColor,proto3" json:"bg_color,omitempty"`
	CornerRadius *CornerRadius `protobuf:"bytes,3,opt,name=corner_radius,json=cornerRadius,proto3" json:"corner_radius,omitempty"`
}

func (x *Button) Reset() {
	*x = Button{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_frontend_UI_Button_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Button) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Button) ProtoMessage() {}

func (x *Button) ProtoReflect() protoreflect.Message {
	mi := &file_protos_frontend_UI_Button_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Button.ProtoReflect.Descriptor instead.
func (*Button) Descriptor() ([]byte, []int) {
	return file_protos_frontend_UI_Button_proto_rawDescGZIP(), []int{0}
}

func (x *Button) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Button) GetBgColor() string {
	if x != nil {
		return x.BgColor
	}
	return ""
}

func (x *Button) GetCornerRadius() *CornerRadius {
	if x != nil {
		return x.CornerRadius
	}
	return nil
}

var File_protos_frontend_UI_Button_proto protoreflect.FileDescriptor

var file_protos_frontend_UI_Button_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x64, 0x2f, 0x55, 0x49, 0x2f, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x55, 0x49, 0x1a, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x55, 0x49, 0x2f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x44, 0x72, 0x69, 0x76, 0x65, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x06, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x67, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x67, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x35, 0x0a,
	0x0d, 0x63, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x5f, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x55, 0x49, 0x2e, 0x43, 0x6f, 0x72, 0x6e, 0x65, 0x72,
	0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x52, 0x0c, 0x63, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x52, 0x61,
	0x64, 0x69, 0x75, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x52, 0x69, 0x6e, 0x6e, 0x65, 0x67, 0x61, 0x6e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64,
	0x2f, 0x55, 0x49, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_frontend_UI_Button_proto_rawDescOnce sync.Once
	file_protos_frontend_UI_Button_proto_rawDescData = file_protos_frontend_UI_Button_proto_rawDesc
)

func file_protos_frontend_UI_Button_proto_rawDescGZIP() []byte {
	file_protos_frontend_UI_Button_proto_rawDescOnce.Do(func() {
		file_protos_frontend_UI_Button_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_frontend_UI_Button_proto_rawDescData)
	})
	return file_protos_frontend_UI_Button_proto_rawDescData
}

var file_protos_frontend_UI_Button_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_frontend_UI_Button_proto_goTypes = []any{
	(*Button)(nil),       // 0: UI.Button
	(*CornerRadius)(nil), // 1: UI.CornerRadius
}
var file_protos_frontend_UI_Button_proto_depIdxs = []int32{
	1, // 0: UI.Button.corner_radius:type_name -> UI.CornerRadius
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_frontend_UI_Button_proto_init() }
func file_protos_frontend_UI_Button_proto_init() {
	if File_protos_frontend_UI_Button_proto != nil {
		return
	}
	file_protos_frontend_UI_ServerDrivenMessages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_frontend_UI_Button_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Button); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_frontend_UI_Button_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_frontend_UI_Button_proto_goTypes,
		DependencyIndexes: file_protos_frontend_UI_Button_proto_depIdxs,
		MessageInfos:      file_protos_frontend_UI_Button_proto_msgTypes,
	}.Build()
	File_protos_frontend_UI_Button_proto = out.File
	file_protos_frontend_UI_Button_proto_rawDesc = nil
	file_protos_frontend_UI_Button_proto_goTypes = nil
	file_protos_frontend_UI_Button_proto_depIdxs = nil
}
