// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0
// source: protos-frontend/ui/LocationConsent.proto

package ui

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// LocationConsent message
//
// Represents a location consent component.
type LocationConsent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// Image associated with the location consent
	Image *Image `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// *
	// Header text for the location consent
	Header *Text `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// Text description for the location consent
	Text *Text `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *LocationConsent) Reset() {
	*x = LocationConsent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_frontend_ui_LocationConsent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocationConsent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationConsent) ProtoMessage() {}

func (x *LocationConsent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_frontend_ui_LocationConsent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationConsent.ProtoReflect.Descriptor instead.
func (*LocationConsent) Descriptor() ([]byte, []int) {
	return file_protos_frontend_ui_LocationConsent_proto_rawDescGZIP(), []int{0}
}

func (x *LocationConsent) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *LocationConsent) GetHeader() *Text {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LocationConsent) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

var File_protos_frontend_ui_LocationConsent_proto protoreflect.FileDescriptor

var file_protos_frontend_ui_LocationConsent_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x64, 0x2f, 0x75, 0x69, 0x2f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e,
	0x73, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x75, 0x69, 0x1a, 0x1e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f,
	0x75, 0x69, 0x2f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f,
	0x75, 0x69, 0x2f, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a,
	0x0f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x74,
	0x12, 0x1f, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x75, 0x69, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x20, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x75, 0x69, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x75, 0x69, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x42, 0x2d, 0x5a, 0x2b, 0x52, 0x69, 0x6e, 0x6e, 0x65, 0x67, 0x61, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x75, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_frontend_ui_LocationConsent_proto_rawDescOnce sync.Once
	file_protos_frontend_ui_LocationConsent_proto_rawDescData = file_protos_frontend_ui_LocationConsent_proto_rawDesc
)

func file_protos_frontend_ui_LocationConsent_proto_rawDescGZIP() []byte {
	file_protos_frontend_ui_LocationConsent_proto_rawDescOnce.Do(func() {
		file_protos_frontend_ui_LocationConsent_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_frontend_ui_LocationConsent_proto_rawDescData)
	})
	return file_protos_frontend_ui_LocationConsent_proto_rawDescData
}

var file_protos_frontend_ui_LocationConsent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_frontend_ui_LocationConsent_proto_goTypes = []interface{}{
	(*LocationConsent)(nil), // 0: ui.LocationConsent
	(*Image)(nil),           // 1: ui.Image
	(*Text)(nil),            // 2: ui.Text
}
var file_protos_frontend_ui_LocationConsent_proto_depIdxs = []int32{
	1, // 0: ui.LocationConsent.image:type_name -> ui.Image
	2, // 1: ui.LocationConsent.header:type_name -> ui.Text
	2, // 2: ui.LocationConsent.text:type_name -> ui.Text
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_frontend_ui_LocationConsent_proto_init() }
func file_protos_frontend_ui_LocationConsent_proto_init() {
	if File_protos_frontend_ui_LocationConsent_proto != nil {
		return
	}
	file_protos_frontend_ui_Image_proto_init()
	file_protos_frontend_ui_Text_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_frontend_ui_LocationConsent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocationConsent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_frontend_ui_LocationConsent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_frontend_ui_LocationConsent_proto_goTypes,
		DependencyIndexes: file_protos_frontend_ui_LocationConsent_proto_depIdxs,
		MessageInfos:      file_protos_frontend_ui_LocationConsent_proto_msgTypes,
	}.Build()
	File_protos_frontend_ui_LocationConsent_proto = out.File
	file_protos_frontend_ui_LocationConsent_proto_rawDesc = nil
	file_protos_frontend_ui_LocationConsent_proto_goTypes = nil
	file_protos_frontend_ui_LocationConsent_proto_depIdxs = nil
}
