// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0
// source: protos-frontend/UI/ServerDrivenMessages.proto

package UI

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define a message structure for corner radius properties.
type CornerRadius struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopLeft     int32 `protobuf:"varint,1,opt,name=top_left,json=topLeft,proto3" json:"top_left,omitempty"`
	TopRight    int32 `protobuf:"varint,2,opt,name=top_right,json=topRight,proto3" json:"top_right,omitempty"`
	BottomLeft  int32 `protobuf:"varint,3,opt,name=bottom_left,json=bottomLeft,proto3" json:"bottom_left,omitempty"`
	BottomRight int32 `protobuf:"varint,4,opt,name=bottom_right,json=bottomRight,proto3" json:"bottom_right,omitempty"`
}

func (x *CornerRadius) Reset() {
	*x = CornerRadius{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_frontend_UI_ServerDrivenMessages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CornerRadius) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CornerRadius) ProtoMessage() {}

func (x *CornerRadius) ProtoReflect() protoreflect.Message {
	mi := &file_protos_frontend_UI_ServerDrivenMessages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CornerRadius.ProtoReflect.Descriptor instead.
func (*CornerRadius) Descriptor() ([]byte, []int) {
	return file_protos_frontend_UI_ServerDrivenMessages_proto_rawDescGZIP(), []int{0}
}

func (x *CornerRadius) GetTopLeft() int32 {
	if x != nil {
		return x.TopLeft
	}
	return 0
}

func (x *CornerRadius) GetTopRight() int32 {
	if x != nil {
		return x.TopRight
	}
	return 0
}

func (x *CornerRadius) GetBottomLeft() int32 {
	if x != nil {
		return x.BottomLeft
	}
	return 0
}

func (x *CornerRadius) GetBottomRight() int32 {
	if x != nil {
		return x.BottomRight
	}
	return 0
}

// Define a message structure for text style properties.
type TextStyle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The font size of the text.
	FontSize float32 `protobuf:"fixed32,1,opt,name=font_size,json=fontSize,proto3" json:"font_size,omitempty"`
	// The font weight of the text
	FontWeight string `protobuf:"bytes,2,opt,name=font_weight,json=fontWeight,proto3" json:"font_weight,omitempty"`
	// The color of the text.
	Color string `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	// Indicates whether the text alignment is centered.
	TextAlignCenter bool `protobuf:"varint,4,opt,name=text_align_center,json=textAlignCenter,proto3" json:"text_align_center,omitempty"`
}

func (x *TextStyle) Reset() {
	*x = TextStyle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_frontend_UI_ServerDrivenMessages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextStyle) ProtoMessage() {}

func (x *TextStyle) ProtoReflect() protoreflect.Message {
	mi := &file_protos_frontend_UI_ServerDrivenMessages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextStyle.ProtoReflect.Descriptor instead.
func (*TextStyle) Descriptor() ([]byte, []int) {
	return file_protos_frontend_UI_ServerDrivenMessages_proto_rawDescGZIP(), []int{1}
}

func (x *TextStyle) GetFontSize() float32 {
	if x != nil {
		return x.FontSize
	}
	return 0
}

func (x *TextStyle) GetFontWeight() string {
	if x != nil {
		return x.FontWeight
	}
	return ""
}

func (x *TextStyle) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *TextStyle) GetTextAlignCenter() bool {
	if x != nil {
		return x.TextAlignCenter
	}
	return false
}

var File_protos_frontend_UI_ServerDrivenMessages_proto protoreflect.FileDescriptor

var file_protos_frontend_UI_ServerDrivenMessages_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x64, 0x2f, 0x55, 0x49, 0x2f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x55, 0x49, 0x22, 0x8a, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x52, 0x61,
	0x64, 0x69, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x5f, 0x6c, 0x65, 0x66, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x6f, 0x70, 0x4c, 0x65, 0x66, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x70, 0x5f, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x74, 0x6f, 0x70, 0x52, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x5f, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x52, 0x69, 0x67, 0x68, 0x74,
	0x22, 0x8b, 0x01, 0x0a, 0x09, 0x54, 0x65, 0x78, 0x74, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x6f, 0x6e, 0x74, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x66, 0x6f, 0x6e, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66,
	0x6f, 0x6e, 0x74, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x66, 0x6f, 0x6e, 0x74, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x61, 0x6c, 0x69, 0x67, 0x6e,
	0x5f, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x74,
	0x65, 0x78, 0x74, 0x41, 0x6c, 0x69, 0x67, 0x6e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x2d,
	0x5a, 0x2b, 0x52, 0x69, 0x6e, 0x6e, 0x65, 0x67, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x55, 0x49, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_frontend_UI_ServerDrivenMessages_proto_rawDescOnce sync.Once
	file_protos_frontend_UI_ServerDrivenMessages_proto_rawDescData = file_protos_frontend_UI_ServerDrivenMessages_proto_rawDesc
)

func file_protos_frontend_UI_ServerDrivenMessages_proto_rawDescGZIP() []byte {
	file_protos_frontend_UI_ServerDrivenMessages_proto_rawDescOnce.Do(func() {
		file_protos_frontend_UI_ServerDrivenMessages_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_frontend_UI_ServerDrivenMessages_proto_rawDescData)
	})
	return file_protos_frontend_UI_ServerDrivenMessages_proto_rawDescData
}

var file_protos_frontend_UI_ServerDrivenMessages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_frontend_UI_ServerDrivenMessages_proto_goTypes = []interface{}{
	(*CornerRadius)(nil), // 0: UI.CornerRadius
	(*TextStyle)(nil),    // 1: UI.TextStyle
}
var file_protos_frontend_UI_ServerDrivenMessages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_frontend_UI_ServerDrivenMessages_proto_init() }
func file_protos_frontend_UI_ServerDrivenMessages_proto_init() {
	if File_protos_frontend_UI_ServerDrivenMessages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_frontend_UI_ServerDrivenMessages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CornerRadius); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_frontend_UI_ServerDrivenMessages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextStyle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_frontend_UI_ServerDrivenMessages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_frontend_UI_ServerDrivenMessages_proto_goTypes,
		DependencyIndexes: file_protos_frontend_UI_ServerDrivenMessages_proto_depIdxs,
		MessageInfos:      file_protos_frontend_UI_ServerDrivenMessages_proto_msgTypes,
	}.Build()
	File_protos_frontend_UI_ServerDrivenMessages_proto = out.File
	file_protos_frontend_UI_ServerDrivenMessages_proto_rawDesc = nil
	file_protos_frontend_UI_ServerDrivenMessages_proto_goTypes = nil
	file_protos_frontend_UI_ServerDrivenMessages_proto_depIdxs = nil
}
