// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0
// source: onboarding/onboarding_responses.proto

package onboarding

import (
	core "Rinnegan/proto-generated/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateCurrentStageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespHeader   *core.ResponseHeader `protobuf:"bytes,1,opt,name=resp_header,json=respHeader,proto3" json:"resp_header,omitempty"`
	CurrentStage OnboardingStage      `protobuf:"varint,2,opt,name=current_stage,json=currentStage,proto3,enum=onboarding.OnboardingStage" json:"current_stage,omitempty"`
}

func (x *UpdateCurrentStageResponse) Reset() {
	*x = UpdateCurrentStageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onboarding_onboarding_responses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCurrentStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrentStageResponse) ProtoMessage() {}

func (x *UpdateCurrentStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_onboarding_responses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrentStageResponse.ProtoReflect.Descriptor instead.
func (*UpdateCurrentStageResponse) Descriptor() ([]byte, []int) {
	return file_onboarding_onboarding_responses_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateCurrentStageResponse) GetRespHeader() *core.ResponseHeader {
	if x != nil {
		return x.RespHeader
	}
	return nil
}

func (x *UpdateCurrentStageResponse) GetCurrentStage() OnboardingStage {
	if x != nil {
		return x.CurrentStage
	}
	return OnboardingStage_ONBOARDING_STAGE_NEW_USER
}

var File_onboarding_onboarding_responses_proto protoreflect.FileDescriptor

var file_onboarding_onboarding_responses_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x6f, 0x6e, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x1a, 0x12, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x2f, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x65,
	0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01, 0x0a, 0x1a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x72, 0x65, 0x73,
	0x70, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x40, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x53,
	0x74, 0x61, 0x67, 0x65, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x52, 0x69, 0x6e, 0x6e, 0x65, 0x67, 0x61, 0x6e, 0x2f, 0x6f,
	0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_onboarding_onboarding_responses_proto_rawDescOnce sync.Once
	file_onboarding_onboarding_responses_proto_rawDescData = file_onboarding_onboarding_responses_proto_rawDesc
)

func file_onboarding_onboarding_responses_proto_rawDescGZIP() []byte {
	file_onboarding_onboarding_responses_proto_rawDescOnce.Do(func() {
		file_onboarding_onboarding_responses_proto_rawDescData = protoimpl.X.CompressGZIP(file_onboarding_onboarding_responses_proto_rawDescData)
	})
	return file_onboarding_onboarding_responses_proto_rawDescData
}

var file_onboarding_onboarding_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_onboarding_onboarding_responses_proto_goTypes = []interface{}{
	(*UpdateCurrentStageResponse)(nil), // 0: onboarding.UpdateCurrentStageResponse
	(*core.ResponseHeader)(nil),        // 1: core.ResponseHeader
	(OnboardingStage)(0),               // 2: onboarding.OnboardingStage
}
var file_onboarding_onboarding_responses_proto_depIdxs = []int32{
	1, // 0: onboarding.UpdateCurrentStageResponse.resp_header:type_name -> core.ResponseHeader
	2, // 1: onboarding.UpdateCurrentStageResponse.current_stage:type_name -> onboarding.OnboardingStage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_onboarding_onboarding_responses_proto_init() }
func file_onboarding_onboarding_responses_proto_init() {
	if File_onboarding_onboarding_responses_proto != nil {
		return
	}
	file_onboarding_onboarding_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_onboarding_onboarding_responses_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCurrentStageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_onboarding_onboarding_responses_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_onboarding_onboarding_responses_proto_goTypes,
		DependencyIndexes: file_onboarding_onboarding_responses_proto_depIdxs,
		MessageInfos:      file_onboarding_onboarding_responses_proto_msgTypes,
	}.Build()
	File_onboarding_onboarding_responses_proto = out.File
	file_onboarding_onboarding_responses_proto_rawDesc = nil
	file_onboarding_onboarding_responses_proto_goTypes = nil
	file_onboarding_onboarding_responses_proto_depIdxs = nil
}
